name: EasterEggs
author: Phloxz
version: 0.2.1
main: EasterEggs.Main
softdepend: [ PlaceholderAPI, Multiverse-Core ]
api-version: 1.13

commands:
  eastereggs:
    description: Reload Config

permissions:
  eastereggs.admin:
    default: op
  eastereggs.top:
    default: true

