name: EasterEggs
author: Phloxz
authors:
  - MrEngMan
version: 0.2.3
main: EasterEggs.Main
softdepend: [ PlaceholderAPI, Multiverse-Core ]
api-version: 1.13

commands:
  eastereggs:
    description: Reload Config

permissions:
  eastereggs.admin:
    default: op
  eastereggs.collect:
    default: true
  eastereggs.top:
    default: true

